@startuml

:Find sensor by id;

if (not found?) then (yes)
  :Answer Not Found;
  stop
endif

:Refresh last_updated;

:Fetch sensor information at the manufacturer;

if (not found?) then (yes)
  :Answer Error <Unknown sensor>;
  stop
endif

:Save sensor with new information;


switch (Needs update?)
case (yes, configuration)
  :Answer Update Configuration;

case (yes, firmware)
  :Answer Update Firmware;

case (no)
  :Answer No Action Needed;

endswitch

stop
@enduml