@startuml

start

:Find sensor by id;

if (not found?) then (yes)
  :Answer Not Found;
  stop
endif

:Refresh last_updated;

:Fetch sensor information at the manufacturer;

if (not found?) then (yes)
  :Answer Error <Unknown sensor>;
  stop
endif

switch (Needs update?)

case (yes, firmware)
  :Notify Needs Firmware Update;
  :Save sensor with new information;
  :Answer Update Firmware;

case (yes, configuration)
  :Notify Needs Configuration Update;
  :Save sensor with new information;
  :Answer Update Configuration;

case (no)
:Save sensor with new information;
  :Answer No Action Needed;



endswitch

stop
@enduml