@startuml

:Find sensor by id;

if (not found?) then (yes)
  :Answer Not Found;
  stop
endif

:Refresh last_updated;

:Fetch sensor information at the manufacturer;

if (not found?) then (yes)
  :Answer Error <Unknown sensor>;
  stop
endif

:Save sensor with new information;


switch (Needs update?)

case (yes, firmware)
  :Notify Needs Firmware Update;
  :Answer Update Firmware;

case (yes, configuration)
  :Notify Needs Configuration Update;
  :Answer Update Configuration;

case (no)
  :Answer No Action Needed;

endswitch

stop
@enduml