@startuml

package application/usecase/shipment {
  class ValidateShipmentCommand {
    -ShipmentId shipmentId (1..1)
    -ShipmentDescription description (1..1)
    -SensorId sensorIds (1..n)
  }

  class ValidateShipmentUseCase {
    -ShipmentRepository shipmentRepository (1..1)
    -ShipmentPolicy shipmentPolicy (1..1)
  }

  class ValidateShipmentUseCaseResult {
    -ValidateShipmentUseCaseResultCode code (1..1)
    -String errors (0..n)
  }

  enum ValidateShipmentUseCaseResultCode {
    VALID,
    INVALID,
    ISSUES_FOUND,
    ERROR
  }

  class ShipmentPolicy


  ValidateShipmentUseCase *-down- ShipmentPolicy
  ValidateShipmentUseCase -right-> ValidateShipmentCommand
  ValidateShipmentUseCase -left-> ValidateShipmentUseCaseResult

  ValidateShipmentUseCaseResult *-down- ValidateShipmentUseCaseResultCode
}

package application/port/shipment {
    interface ShipmentRepository
}

package domain/shipment {
  class ShipmentId
  class ShipmentDescription
}

package domain/sensor {
  class SensorId
}

ValidateShipmentCommand o-down- ShipmentId
ValidateShipmentCommand o-down-- ShipmentDescription
ValidateShipmentCommand o-up- SensorId
ValidateShipmentUseCase o-up- ShipmentRepository
@enduml