@startuml

package application/usecase/sensor {
  class CheckSensorStatusCommand {
    -SensorId SensorId (1..1)
  }

  class CheckSensorStatusUseCase {
    -SensorManufacturerGateway sensorManufacturerGateway (1..1)
  }

  class CheckSensorStatusUseCaseResult {
    -CheckSensorStatusUseCaseResultCode code (1..1)
    -String errors (0..n)
  }

  enum CheckSensorStatusUseCaseResultCode {
    NOT_REGISTERED,
    NO_ACTION_NEEDED,
    UPDATE_CONFIGURATION,
    UPDATE_FIRMWARE,
    ERROR
  }

  CheckSensorStatusUseCase -right-> CheckSensorStatusCommand
  CheckSensorStatusUseCase -left-> CheckSensorStatusUseCaseResult

  CheckSensorStatusUseCaseResult *-down- CheckSensorStatusUseCaseResultCode
}

package application/port/sensor {
    interface SensorManufacturerGateway
    interface SensorRepository
}

package domain/sensor {
  class SensorId
}

CheckSensorStatusCommand o-up- SensorId
CheckSensorStatusUseCase o-up- SensorManufacturerGateway
CheckSensorStatusUseCase o-up- SensorRepository
@enduml