@startuml

package application/usecase/sensor {
  class UpdateSensorStatusCommand {
    -SensorId SensorId (1..1)
  }

  class UpdateSensorStatusUseCase {
    -SensorManufacturerGateway sensorManufacturerGateway (1..1)
  }

  class UpdateSensorStatusUseCaseResult {
    -UpdateSensorStatusUseCaseResultCode code (1..1)
    -String errors (0..n)
  }

  enum UpdateSensorStatusUseCaseResultCode {
    NOT_REGISTERED,
    NO_ACTION_NEEDED,
    CONFIGURATION_UPDATE_REQUIRED,
    FIRMWARE_UPDATE_REQUIRED,
    ERROR
  }

  UpdateSensorStatusUseCase -right-> UpdateSensorStatusCommand
  UpdateSensorStatusUseCase -left-> UpdateSensorStatusUseCaseResult

  UpdateSensorStatusUseCaseResult *-down- UpdateSensorStatusUseCaseResultCode
}

package application/port/sensor {
    interface SensorManufacturerGateway
    interface SensorRepository
}

package domain/sensor {
  class SensorId
}

UpdateSensorStatusCommand o-up- SensorId
UpdateSensorStatusUseCase o-up- SensorManufacturerGateway
UpdateSensorStatusUseCase o-up- SensorRepository
@enduml