@startuml

package application/usecase/sensor {
  class UpdateTaskStatusCommand {
    -SensorId sensorId (1..1)
    -TaskId taskId (1..1)
  }

  class UpdateTaskStatusUseCase {
    -SensorManufacturerGateway sensorManufacturerGateway (1..1)
    -SensorRepository sensorRepository (1..1)
    -TaskRepository taskRepository (1..1)
  }

  class UpdateTaskStatusUseCaseResult {
    -UpdateTaskStatusUseCaseResultCode code (1..1)
    -String errors (0..n)
  }

  enum UpdateTaskStatusUseCaseResultCode {
    SENSOR_NOT_FOUND,
    SENSOR_NOT_KNOWN_BY_MANUFACTURER,
    TASK_NOT_FOUND,
    DONE,
    ERROR
  }

  UpdateTaskStatusUseCase -right-> UpdateTaskStatusCommand
  UpdateTaskStatusUseCase -left-> UpdateTaskStatusUseCaseResult

  UpdateTaskStatusUseCaseResult *-down- UpdateTaskStatusUseCaseResultCode
}

package application/port/sensor {
    interface SensorManufacturerGateway
    interface SensorRepository
}

package application/port/task {
    interface TaskRepository
}

package domain/sensor {
  class SensorId
}

package domain/task {
  class TaskId
}

UpdateTaskStatusCommand o-up- SensorId
UpdateTaskStatusCommand o-up- TaskId
UpdateTaskStatusUseCase o-up- SensorManufacturerGateway
UpdateTaskStatusUseCase o-up- SensorRepository
UpdateTaskStatusUseCase o-up- TaskRepository
@enduml