@startuml

package shared {
    abstract class DomainEvent {
        -LocalDateTime creationDateTime
        -String name
    }
}

package shipment {
  class Shipment {
    -ShipmentId id (1..1)
    -ShipmentDescription description (1..1)
    -SensorId sensorIds (1..n)
    -DomainEvent events (1..n)
  }
  
  class ShipmentId {
    -String value (1..1)
  }

  class ShipmentDescription {
  -String value (1..1)
  }

  Shipment o-up- ShipmentId
  Shipment o-up- ShipmentDescription

  Shipment o-right- DomainEvent
}


package Sensor {
    class Sensor {
      -SensorId id (1..1)
      -Firmware firmware (1..1)
      -Configuration configuration (1..1)
      -SensorTasksStatus tasksStatus (1..1)
      -SensorActivityStatus activityStatus (1..1)
      -DomainEvent events (1..n)
    }

    class SensorId {
      -String value (1..1)
    }

    class Firmware {
      -FirmwareVersion version (1..1)
    }

    class FirmwareVersion {
      -Integer day (1..1)
      -Integer month (1..1)
      -Integer year (1..1)
      -Integer serialNumber (1..1)
    }

    class Configuration {
      -FileName name (1..1)
    }

    enum SensorTasksStatus {
      IDLE,
      AWAITING,
      UPDATING
    }

    enum SensorActivityStatus {
      ONLINE,
      DISCONNECTED,
      ERROR
    }

    Sensor *-left- SensorId
    Sensor *-down- Firmware
    Sensor *-down-- Configuration
    Sensor *-down- SensorTasksStatus
    Sensor *-down-- SensorActivityStatus
    Sensor *-up- DomainEvent
    Firmware *-down- FirmwareVersion
}

package Task {
    class Task {
      -SensorId sensorId (1..1)
      -TaskId id (1..1)
      -UpdateFile file (1..1)
      -TaskType type (1..1)
      -TaskStatus status (1..1)
    }

    class TaskId {
      -String value (1..1)
    }

    class UpdateFile {
      -FileName name (1..1)
    }

    enum TaskType {
      UPDATE_CONFIGURATION,
      UPDATE_FIRMWARE
    }

    enum TaskStatus {
      PENDING,
      COMPLETED,
      ERROR,
      ONGOING
    }

    Task *-right- TaskId
    Task *-left- UpdateFile
    Task *-down- TaskType
    Task *-down- TaskStatus
}

Shipment o-down- SensorId
Task o-up- SensorId



@enduml