@startuml

package domain/shared as ds {
  class DomainEvent
}

package shipment/events as she {
  class ShipmentReceived {
  }

  class ShipmentValidated {
  }

  class ShipmentNotValidated {
    -String reason (1..1)
  }

  class ShipmentValidationFailed {
    -String reason (1..1)
  }

}

package sensor/events as see {
  class SensorRegistered {}

  package firmware {
      class NeedsFirmwareUpdate

      class FirmwareUpdateScheduled {
        -FirmwareVersion oldVersion (1..1)
        -FirmwareVersion newVersion (1..1)
      }

      class FirmwareUpdated {
        -FirmwareVersion oldVersion (1..1)
        -FirmwareVersion newVersion (1..1)
      }

      class FirmwareUpdateCancelled {
        -FirmwareVersion oldVersion (1..1)
        -FirmwareVersion newVersion (1..1)
      }

      class FirmwareUpdateFailed {
        -FirmwareVersion oldVersion (1..1)
        -FirmwareVersion newVersion (1..1)
        -String reason (1..1)
      }
  }

  package configuration {

    class NeedsConfigurationUpdate

    class ConfigurationUpdateScheduled {
      -Configuration oldVersion (1..1)
      -Configuration newVersion (1..1)
    }

    class ConfigurationUpdated {
      -Configuration oldVersion (1..1)
      -Configuration newVersion (1..1)
    }

    class ConfigurationUpdateCancelled {
      -Configuration oldVersion (1..1)
      -Configuration newVersion (1..1)
    }

    class ConfigurationUpdateFailed {
      -Configuration oldVersion (1..1)
      -Configuration newVersion (1..1)
      -String reason (1..1)
    }
  }
}

she -- DomainEvent
see -- DomainEvent

@enduml