@startuml

package domain/shared as ds {
  class DomainEvent
}

package shipment/events as she {
  class ShipmentReceived {
  }

  class ShipmentValidated {
  }

  class ShipmentNotValidated {
    -String reason (1..1)
  }

  class ShipmentValidationFailed {
    -String reason (1..1)
  }
}

package sensor/events as see {
  class SensorRegistered {}

  enum Version {
    -String value (1..1)
  }

  class FirmwareUpdateRequired {
    -UpdateType type (1..1)
    -Version oldVersion (1..1)
  }

  class FirmwareUpdateScheduled {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }

  class FirmwareUpdateNotScheduled {
      -Version oldVersion (1..1)
      -Version newVersion (1..1)
      -String reason (1..1)
    }

  class FirmwareUpdated {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }

  class FirmwareUpdateCancelled {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }

  class FirmwareUpdateFailed {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
    -String reason (1..1)
  }
  
  class ConfigurationUpdateRequired {
    -UpdateType type (1..1)
    -Version oldVersion (1..1)
  }

  class ConfigurationUpdateScheduled {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }

  class ConfigurationUpdateNotScheduled {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
    -String reason (1..1)
  }
  
  class ConfigurationUpdated {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }
  
  class ConfigurationUpdateCancelled {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
  }
  
  class ConfigurationUpdateFailed {
    -Version oldVersion (1..1)
    -Version newVersion (1..1)
    -String reason (1..1)
  }
}

she -- DomainEvent
see -- DomainEvent

@enduml